remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "air"  # "default", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

locale: "en-US"

repository: "techyuzhu/blog"

title: "Babbling of an Engineer"
name: "Yuzhu Shen"
description: "Some thoughts and observations of a software engineer."
url: "https://techyuzhu.github.io"
timezone: "America/Los_Angeles"

author:
  name     : "Yuzhu Shen"
  #avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Software engineer."
  location : "SF bay area, USA"

search: true
lunr:
  search_within_pages: true
  search_full_content: true

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOKx8m2Q"  # Shown during giscus setup at https://giscus.app
    category_name        : "Announcements"  # Full text name of the category
    category_id          : "DIC_kwDOKx8m2c4CcQCo"  # Shown during giscus setup at https://giscus.app
    discussion_term      : "pathname"  # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : '1'  # '1' for enabled (default), '0' for disabled
    theme                : "preferred_color_scheme"  # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      # read_time: true
      comments: true
      share: true
      related: true
      header:
        image: /assets/images/header_grand_canyon_2.jpg
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      header:
        image: /assets/images/header_grand_canyon.jpg
